# Generated by Django 2.1.3 on 2018-11-19 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Saree',
            new_name='Product',
        ),
    ]
