# Generated by Django 2.1.3 on 2018-11-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0005_paytmhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paytmhistory',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='discount_rate',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.DeleteModel(
            name='PaytmHistory',
        ),
    ]
