# Generated by Django 2.1.3 on 2018-11-24 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0006_auto_20181124_1011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_percent',
            field=models.IntegerField(),
        ),
    ]
