# Generated by Django 2.1.3 on 2018-11-28 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0008_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
