# Generated by Django 2.1.3 on 2018-12-24 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0010_paytmhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_payment_paytm', to=settings.AUTH_USER_MODEL),
        ),
    ]
