# Generated by Django 2.1.3 on 2018-12-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textiles', '0011_auto_20181224_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paytmhistory',
            name='BANKTXNID',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='BANK TXN ID'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='RESPCODE',
            field=models.CharField(max_length=500, verbose_name='RESP CODE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNDATE',
            field=models.CharField(max_length=250, verbose_name='TXN DATE'),
        ),
        migrations.AlterField(
            model_name='paytmhistory',
            name='TXNID',
            field=models.CharField(max_length=500, verbose_name='TXN ID'),
        ),
    ]
